//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualFlightsBase
    {
        public long ID { get; set; }
        public int SeatsCount { get; set; }
        public int TicketsSold { get; set; }
        public int TicketsReturned { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArivalDateTime { get; set; }
        public Nullable<long> Aircraft_ID { get; set; }
        public Nullable<long> Flight_ID { get; set; }
        public Nullable<long> FlightStatus_ID { get; set; }
    
        public virtual AircraftsBase AircraftsBase { get; set; }
        public virtual FlightsBase FlightsBase { get; set; }
        public virtual FlightStatusesBase FlightStatusesBase { get; set; }
    }
}
