//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftsBase
    {
        public AircraftsBase()
        {
            this.ActualFlightsBase = new HashSet<ActualFlightsBase>();
        }
    
        public long ID { get; set; }
        public int NumberOfFlights { get; set; }
        public Nullable<long> AircraftType_ID { get; set; }
        public Nullable<long> TechCheck_ID { get; set; }
    
        public virtual ICollection<ActualFlightsBase> ActualFlightsBase { get; set; }
        public virtual AircraftTypesBase AircraftTypesBase { get; set; }
        public virtual TechChecksBase TechChecksBase { get; set; }
    }
}
