//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildsBase
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public long ParentRefId { get; set; }
    
        public virtual EmployeesBase EmployeesBase { get; set; }
    }
}
