//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentsBase
    {
        public DepartmentsBase()
        {
            this.EmployeesBase1 = new HashSet<EmployeesBase>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Chief_ID { get; set; }
    
        public virtual EmployeesBase EmployeesBase { get; set; }
        public virtual ICollection<EmployeesBase> EmployeesBase1 { get; set; }
    }
}
