//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightStatusesBase
    {
        public FlightStatusesBase()
        {
            this.ActualFlightsBase = new HashSet<ActualFlightsBase>();
        }
    
        public long ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<ActualFlightsBase> ActualFlightsBase { get; set; }
    }
}
