//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightsBase
    {
        public FlightsBase()
        {
            this.ActualFlightsBase = new HashSet<ActualFlightsBase>();
            this.SceduleBase = new HashSet<SceduleBase>();
        }
    
        public long ID { get; set; }
        public int PassengersCount { get; set; }
        public Nullable<long> Category_ID { get; set; }
        public Nullable<long> Route_ID { get; set; }
    
        public virtual ICollection<ActualFlightsBase> ActualFlightsBase { get; set; }
        public virtual ArivalAirportsBase ArivalAirportsBase { get; set; }
        public virtual FlightCategoriesBase FlightCategoriesBase { get; set; }
        public virtual ICollection<SceduleBase> SceduleBase { get; set; }
    }
}
