//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalChecksBase
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Valid { get; set; }
        public Nullable<long> Employee_ID { get; set; }
    
        public virtual EmployeesBase EmployeesBase { get; set; }
    }
}
