//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseLabEntities : DbContext
    {
        public DataBaseLabEntities()
            : base("name=DataBaseLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ActualFlightsBase> ActualFlightsBase { get; set; }
        public virtual DbSet<AircraftsBase> AircraftsBase { get; set; }
        public virtual DbSet<AircraftTypesBase> AircraftTypesBase { get; set; }
        public virtual DbSet<ArivalAirportsBase> ArivalAirportsBase { get; set; }
        public virtual DbSet<BrigadesBase> BrigadesBase { get; set; }
        public virtual DbSet<ChildsBase> ChildsBase { get; set; }
        public virtual DbSet<DepartmentsBase> DepartmentsBase { get; set; }
        public virtual DbSet<EmployeesBase> EmployeesBase { get; set; }
        public virtual DbSet<FlightCategoriesBase> FlightCategoriesBase { get; set; }
        public virtual DbSet<FlightsBase> FlightsBase { get; set; }
        public virtual DbSet<FlightStatusesBase> FlightStatusesBase { get; set; }
        public virtual DbSet<MedicalChecksBase> MedicalChecksBase { get; set; }
        public virtual DbSet<PositionsBase> PositionsBase { get; set; }
        public virtual DbSet<SceduleBase> SceduleBase { get; set; }
        public virtual DbSet<TechChecksBase> TechChecksBase { get; set; }
    }
}
