//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class SceduleBase
    {
        public long ID { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArivalDateTime { get; set; }
        public int Price { get; set; }
        public Nullable<long> AircraftType_ID { get; set; }
        public Nullable<long> Flight_ID { get; set; }
    
        public virtual AircraftTypesBase AircraftTypesBase { get; set; }
        public virtual FlightsBase FlightsBase { get; set; }
    }
}
