//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFormsAndTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechChecksBase
    {
        public TechChecksBase()
        {
            this.AircraftsBase = new HashSet<AircraftsBase>();
        }
    
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool MustBeFixed { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<AircraftsBase> AircraftsBase { get; set; }
    }
}
